version: '3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./volumes/db/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: drawbot_user
      POSTGRES_PASSWORD: drawbot_pass
      POSTGRES_DB: drawbot_db

  redis:
    image: redis
    restart: always
    volumes:
      - ./volumes/storage/redis/data:/var/lib/redis/data
    ports:
      - 6379:6379

  web:
    build: .
    container_name: web
    ports:
      - 8000:8000
    volumes:
      - ./webapp:/webapp
      - ./bot:/bot
    working_dir: /bot
    depends_on:
      - db

    command: python app.py
#    command: gunicorn --bind=0.0.0.0:8000 --name=webapp webapp.wsgi:application --reload -w 2