version: '3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./volumes/db/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: drawbot_user
      POSTGRES_PASSWORD: drawbot_pass
      POSTGRES_DB: drawbot_db

  redis:
    image: redis
    restart: always
    volumes:
      - ./volumes/storage/redis/data:/var/lib/redis/data
    ports:
      - 6379:6379

  webapp:
    build: .
    container_name: webapp
    ports:
      - 8080:8080
    volumes:
      - ./webapp:/webapp
      - ./bot:/bot
    working_dir: /webapp
    depends_on:
      - db
